# Generated by Django 4.1 on 2022-08-22 14:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0001_initial"),
        ("reviews", "0002_rename_user_review_critic_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("movie_id", "critic")},
        ),
    ]
